/* ============================================================================
   FamilyPlanz — the marks.

   One source of truth for every brand mark, so a page and the rasteriser can
   never disagree. scripts/build-brand-rasters.mjs renders straight from here
   into static/brand/, and brand-check.mjs fails if what is on disk drifts from
   what is here.

   Tokens are copied EXACTLY from prototypes/app-ui/proto.css, which is the
   one palette in this repo that the whole estate already agrees on:

     canvas  #f8f6f3   terracotta #c45e38   terracotta-hover #a14d32
     blush   #fed5cf   peach      #f1b598   sky            #bedae3
     mint    #c4e9da   ink        #0f172a   ink-soft       #334155

   Every mark is 512x512 with the tile filling the whole viewBox, because the
   maskable icon is generated by the same paths — see maskable().

   THE VARIANTS ARE THE RECORD. Three candidates, one synthesis; a review
   produces a synthesis, not a patch. The losers stay on disk.
   ========================================================================== */

/* Named EXACTLY as the calendar-ui tokens are named — `--blue`, not `--sky`;
 * `--s900`, not `--ink`. The values were always right; the names were mine, and
 * a token that does not exist in the palette cannot be checked against it.
 * brand-check.mjs §1 fails on any hex here that is not in calendar-ui's :root. */
export const T = {
	canvas: '#f8f6f3',
	terracotta: '#c45e38',
	terracottaHover: '#a14d32',
	blush: '#fed5cf',
	peach: '#f1b598',
	peachInk: '#84412e',
	blue: '#bedae3',
	/* Added 2026-09-30 for the header band the owner asked for. `--blue-ink` in
	 * proto.css, and the same value already ships in the app as --mp-blue-ink in
	 * src/lib/marketing/theme.css. T.blue is a TINT: everywhere in this repo
	 * #bedae3 appears only as a background with #366d7e as the text on top, so it
	 * is a surface, not an ink. A #bedae3 band on the #f8f6f3 page is a surface
	 * on a surface — lower contrast than the #fed5cf band it replaced. Both were
	 * measured at 16px; see docs/issues/095. */
	blueInk: '#366d7e',
	mint: '#c4e9da',
	s900: '#0f172a'
};

/** The rounded tile every mark sits on. Squircle-ish: 116/512 ≈ 0.227. */
const tile = (id) => `
	<defs>
		<linearGradient id="${id}-tile" x1="0" y1="0" x2="0" y2="1">
			<stop offset="0" stop-color="${T.terracotta}"/>
			<stop offset="1" stop-color="${T.terracottaHover}"/>
		</linearGradient>
	</defs>
	<rect width="512" height="512" rx="116" fill="url(#${id}-tile)"/>`;

const svg = (id, body, extra = '') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512" role="img"${extra}>${body}</svg>`;

/* ── A · "Page" ────────────────────────────────────────────────────────────
   The literal mark: a calendar page on a tile, carrying three dots — two
   adults and a child between them. Complete, and complete is the risk: a
   band, three dots and a bar is four things in nine pixels at favicon size. */
const A_PAGE = (id) => `
	<clipPath id="${id}-page"><rect x="104" y="112" width="304" height="288" rx="34"/></clipPath>
	<g clip-path="url(#${id}-page)">
		<rect x="104" y="112" width="304" height="288" rx="34" fill="${T.canvas}"/>
		<rect x="104" y="112" width="304" height="94" fill="${T.blush}"/>
	</g>
	<circle cx="180" cy="298" r="31" fill="${T.terracotta}"/>
	<circle cx="256" cy="298" r="24" fill="${T.terracotta}"/>
	<circle cx="332" cy="298" r="31" fill="${T.terracotta}"/>
	<rect x="152" y="340" width="208" height="26" rx="13" fill="${T.peach}"/>`;

/* ── B · "Roof" ────────────────────────────────────────────────────────────
   Home and calendar fused: a roof over a four-cell grid, one cell filled.
   Says "our house's week" more literally than A, and loses the people. */
const B_ROOF = (id) => `
	<path d="M124 272 L256 152 L388 272" fill="none" stroke="${T.canvas}" stroke-width="34"
		stroke-linecap="round" stroke-linejoin="round"/>
	<rect x="130" y="258" width="252" height="142" rx="22" fill="${T.canvas}"/>
	<rect x="168" y="294" width="46" height="46" rx="13" fill="${T.blue}"/>
	<rect x="298" y="294" width="46" height="46" rx="13" fill="${T.blue}"/>
	<rect x="168" y="352" width="46" height="46" rx="13" fill="${T.peach}"/>
	<rect x="298" y="352" width="46" height="46" rx="13" fill="${T.blue}"/>`;

/* ── C · "Halo" ────────────────────────────────────────────────────────────
   A week as a ring, today as the filled bead on top, the family as three small
   dots at the centre. The most abstract, the most confident at 16px, and the
   furthest from saying "calendar". */
const C_HALO = (id) => `
	<circle cx="256" cy="256" r="104" fill="none" stroke="${T.canvas}" stroke-width="40"/>
	<circle cx="256" cy="152" r="32" fill="${T.peach}"/>
	<circle cx="212" cy="256" r="16" fill="${T.canvas}"/>
	<circle cx="256" cy="256" r="16" fill="${T.canvas}"/>
	<circle cx="300" cy="256" r="16" fill="${T.canvas}"/>`;

/* The synthesis, redrawn on 2026-09-30 after the round-1 review said "make it
 * look more like a calendar". The old one was a page with a blush band and
 * three circles — no top edge, no grid, no ring. At 16px (÷32) the circles were
 * r=35 → a 2px three-dot blob that read as a face, and nothing on the
 * silhouette said "calendar" at any size.
 *
 * Geometry is the owner's direction of 2026-09-30, in two parts. The grid is
 * 4 across by 3 down — twelve cells — with ONE carrying the "today" accent,
 * because a grid where every cell weighs the same reads as texture. And the
 * page carries a header band, in blue, which the owner asked for AFTER this band
 * had been measured out on 16px evidence. The reversal is the owner's call and
 * the cost is re-measured below and recorded, not dropped again.
 *
 * What survives 16px:
 *   - the page         canvas on terracotta: the one strong shape.
 *   - two ink rings    the calendar signifier, the only element that survives
 *                      1px. INK, not terracotta: a terracotta ring on the
 *                      terracotta tile is invisible.
 *   - the header band  T.blueInk, which is why it survives at all — see T.
 *   - the 4 x 3 grid   1.75px cells with 0.625px gaps: texture, not a grid.
 *   - the accent cell  the one feature the eye is meant to find.
 *
 * THE BAND IS BACK, and the page grew to carry it: 324 x 306 instead of
 * 336 x 280. The cells stay 56 units, because 56 is the largest square cell that
 * fits four across, and the cells were never what moved. Cells are square on
 * purpose: a rectangular cell's SHORT side is what has to survive 16px, and a
 * square maximises it for the area.
 *
 * THE COLOUR IS T.blueInk (#366d7e), NOT T.blue (#bedae3), which is a deviation
 * from the literal instruction "make it the blue color". The reason is measured,
 * not aesthetic: #bedae3 is a tint, and against the #f8f6f3 page it is a surface
 * on a surface — measurably lower contrast than the #fed5cf blush it replaced.
 * Across this whole repo #bedae3 only ever appears as a background with #366d7e
 * as the text on it. Both were rasterised at 16px and the numbers are in
 * docs/issues/095, so the owner can see what the literal reading costs and
 * reverse this if they disagree.
 *
 * The three family circles are gone. A family of three cannot be told apart from
 * a face, a cluster or a blob at the size an icon is judged at, and carrying it
 * is what cost this mark its calendar reading. The family is carried by the
 * name now.
 *
 * Envelope x 94..418, y 112..464. Worst sharp corner r=264.1 from the centre,
 * which is why maskable() scales by 0.72 — see its comment. */
const SYNTH_BODY = (id) => {
	/* 4 across by 3 down, 56 units with 20 between: 4·56 + 3·20 = 284 of grid
	 * inside a 324 page, 20 of padding each side. */
	const CELLS = [228, 304, 380].flatMap((y) => [114, 190, 266, 342].map((x) => [x, y]));
	/* the "today" cell: the middle of the grid, so the accent does not have to
	 * compete with the rings or the band for the eye at the top. */
	const ACCENT = [190, 304];
	const cell = ([x, y]) =>
		`<rect x="${x}" y="${y}" width="56" height="56" rx="14" fill="${
			x === ACCENT[0] && y === ACCENT[1] ? T.terracotta : T.peach
		}"/>`;
	return `
	<clipPath id="${id}-page"><rect x="94" y="158" width="324" height="306" rx="36"/></clipPath>
	<g clip-path="url(#${id}-page)">
		<rect x="94" y="158" width="324" height="306" rx="36" fill="${T.canvas}"/>
		<rect x="94" y="158" width="324" height="50" fill="${T.blueInk}"/>
		${CELLS.map(cell).join('')}
	</g>
	<rect x="158" y="112" width="44" height="92" rx="22" fill="${T.s900}"/>
	<rect x="310" y="112" width="44" height="92" rx="22" fill="${T.s900}"/>`;
};

/* ── the marks ───────────────────────────────────────────────────────────── */

export const MARKS = {
	a: {
		id: 'a',
		name: 'A · Page',
		thesis: 'A calendar page that carries the family. Complete, and complete is the risk.',
		svg: svg('a', tile('a') + A_PAGE('a'))
	},
	b: {
		id: 'b',
		name: 'B · Roof',
		thesis: 'A roof over a week. Says "our house" more literally, and loses the people.',
		svg: svg('b', tile('b') + B_ROOF('b'))
	},
	c: {
		id: 'c',
		name: 'C · Halo',
		thesis: 'A week as a ring, today as the bead on top. Most confident at 16px, furthest from "calendar".',
		svg: svg('c', tile('c') + C_HALO('c'))
	},
	mark: {
		id: 'mark',
		name: 'Synthesis',
		thesis: 'A without the bar, with the family given real weight. The shipping candidate.',
		svg: svg('mark', tile('mark') + SYNTH_BODY('mark'))
	}
};

/**
 * The maskable icon. Android crops a maskable icon to a circle inscribed in the
 * middle 80% of the canvas, so the same paths are scaled to 80% about the
 * centre and the tile is re-drawn full-bleed underneath to fill whatever the
 * mask leaves. Without that, the tile's own rounded corners get cut and the
 * icon reads as a circle with orange corners around it.
 *
 * The tile used to be the SCALED one drawn over a flat #c45e38 rect, which put
 * a visible colour break at y=384 (the 80% line) and contradicted the sentence
 * above. It is now the real full-bleed tile, the same way ogCard() does it — so
 * "full-bleed" is true in the code as well as on the page.
 *
 * Safe area, measured not assumed. Android's safe circle is r=204.8 (40% of
 * 512). SYNTH_BODY's worst SHARP corner is r=263.6 from the centre (measured by
 * parsing every rect in the drawn body, not estimated), so the old 0.8 scale
 * put it at 210.9 — OUTSIDE the safe circle, and the bottom corners of the page
 * were being eaten. At 0.72 it lands at r=189.8, which is 15.0 units of
 * clearance. If a future redraw grows, re-measure this rather than trusting 0.72.
 */
export function maskable(id = 'maskable') {
	return svg(
		id,
		tile(id) +
			`<g transform="translate(256 256) scale(.72) translate(-256 -256)">` +
			SYNTH_BODY(id) +
			`</g>`
	);
}

/** The og card, 1200x630, as one SVG. Text is set in the system rounded stack
 *  the app already uses, so the raster and the page agree with no webfont. */
export const OG = {
	width: 1200,
	height: 630,
	/* The four headlines, each with its breaks SET rather than left to the card:
	   a card generator cannot measure text, and a headline that runs off the
	   right edge is only visible once it has already been rendered. Broken at
	   the point a person would break it, not at the width limit.

	   Rendered at HEAD 74 in the system rounded stack, a line holds roughly 26
	   characters. h1 and h4 are over that, which is why they are two lines. */
	heads: [
		{
			id: 'h1',
			head: 'Where family schedules\ncome together.',
			sub: 'One shared calendar for the people, the plans,\nand the jobs nobody else remembered.',
			note: 'The live H1, carried over so the card is judged against the real thing rather than a strawman.'
		},
		{
			id: 'h2',
			head: 'Everyone’s week, on one page.',
			sub: 'Events, RSVPs and the grocery list — the whole\nhousehold, in one warm place.',
			note: 'Shortest of the four. One line, so the card has the most air.'
		},
		{
			id: 'h3',
			head: 'Stop being the family calendar.',
			sub: 'The one who remembers. Give the week to\neverybody and keep your own head.',
			note: 'Names the pain in the second person, which is who the searcher is.'
		},
		{
			id: 'h4',
			head: 'The week your family\nactually has.',
			sub: 'Soccer, conferences, date night, and whose turn\nit is — held by everyone, missed by no one.',
			note: 'Concrete, and the most specific. The two-line head is the risk to look at.'
		}
	]
};

/* Single quotes inside the stack, not double: this string lands in a
   double-quoted font-family attribute, and a bare " ends the attribute and
   makes the whole document unparseable. SVG does not have CSS escaping here. */
const FONT = "ui-rounded, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";

/* The card's type scale, as numbers rather than as they are written inline,
   because the layout below is arithmetic on them. */
const HEAD = 74;
const HEAD_LEAD = 84;
const SUB = 30;
const SUB_LEAD = 42;
const PAD = 72;
/** the text block sits between the lockup and the rule, and is centred in it */
const BLOCK_TOP = 232;
const BLOCK_BOTTOM = 528;

/**
 * The og card, 1200x630.
 *
 * `head` and `sub` may carry \n. A card generator that never measures text has
 * to be told where the breaks are, and told where the block starts — the first
 * version guessed both and collided the headline with the wordmark. So the
 * caller supplies the breaks (OG.heads carries them) and this computes the
 * position from the resulting line count.
 */
export function ogCard({ head, sub }) {
	const headLines = head.split('\n');
	const subLines = sub.split('\n');
	// cap height plus descender, not the font size: the box that has to fit
	const blockH = HEAD + (headLines.length - 1) * HEAD_LEAD + 30 + (subLines.length - 1) * SUB_LEAD;
	const first = BLOCK_TOP + Math.max(0, (BLOCK_BOTTOM - BLOCK_TOP - blockH) / 2);
	return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630" role="img">
		<defs>
			<linearGradient id="og-bg" x1="0" y1="0" x2="1" y2="1">
				<stop offset="0" stop-color="${T.canvas}"/>
				<stop offset="1" stop-color="${T.blush}"/>
			</linearGradient>
			<clipPath id="og-mark"><rect width="512" height="512" rx="116"/></clipPath>
		</defs>
		<rect width="1200" height="630" fill="url(#og-bg)"/>
		<circle cx="1090" cy="90" r="230" fill="${T.peach}" opacity=".35"/>
		<circle cx="60" cy="620" r="190" fill="${T.blue}" opacity=".45"/>
		<g transform="translate(${PAD} 60) scale(.203125)">
			<g clip-path="url(#og-mark)">
				<rect width="512" height="512" rx="116" fill="${T.terracotta}"/>
				<g transform="translate(256 256) scale(.8) translate(-256 -256)">${SYNTH_BODY('og')}</g>
			</g>
		</g>
		<text x="200" y="128" font-family="${FONT}" font-size="40" font-weight="800"
			letter-spacing="-0.5" fill="${T.s900}">Family Planz</text>
		<text x="200" y="172" font-family="${FONT}" font-size="26" font-weight="600"
			fill="${T.s900}" opacity=".62">The shared family calendar</text>
		${headLines
			.map(
				(l, i) =>
					`<text x="${PAD}" y="${first + i * HEAD_LEAD}" font-family="${FONT}" font-size="${HEAD}" font-weight="800" letter-spacing="-2" fill="${T.s900}">${l}</text>`
			)
			.join('\n\t\t')}
		${subLines
			.map(
				(l, i) =>
					`<text x="${PAD}" y="${first + HEAD + 30 + i * SUB_LEAD}" font-family="${FONT}" font-size="${SUB}" font-weight="500" fill="${T.s900}" opacity=".7">${l}</text>`
			)
			.join('\n\t\t')}
		<rect x="${PAD}" y="556" width="120" height="8" rx="4" fill="${T.terracotta}"/>
		<text x="${PAD}" y="600" font-family="${FONT}" font-size="25" font-weight="700"
			fill="${T.terracotta}">familyplanz.com</text>
	</svg>`;
}
