-- 009 - Bill receipts (issue 010): attachments table + bills.attachment_id.
--
-- DEPRECATED (2026-09-07): the user decreed PROCESS-AND-DELETE for receipt
-- images — never uploaded, never stored. This migration is superseded by
-- sql/010-drop-receipt-storage.sql, which drops everything created here.
-- Kept for history only. Do not apply.
